using UnityEngine;
using System.Collections;

public class ZOrderFix : MonoBehaviour {

	//public tk2dSprite currentSprite;

	public int sortingOrder = 0;

	public int MaximunY = 10000;

	// Use this for initialization
	void Start () 
	{
		//
		// based on the Y position
		//

		sortingOrder = MaximunY - (int)this.transform.position.y;

		//currentSprite.SortingOrder = sortingOrder;
	}
	
	// Update is called once per frame
	void Update () 
	{
//		if(sortingOrder != currentSprite.SortingOrder)
//		{
//			//currentSprite.SortingOrder = sortingOrder;
//
//			Debug.Log("esto esta pasando?");
//		}
	}
}
